version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore FYP/FYP.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet build FYP/FYP.csproj

  post_build:
    commands:
      - echo Publish started on `date`
      - mkdir source
      - dotnet publish -c Release -o ./source FYP/FYP.csproj
      - ls source

artifacts:
  files:
    - '**/*'
  base-directory: 'source'
